monitor.alsa.rules = [
  {
    matches = [
      {
        ## This matches the node name using a regular expression
        node.name = "~alsa_output.platform-sound.*Speaker.*"
      }
    ]
    actions = {
      update-props = {
        ## Disables the hardware mixer and enables the software mixer
        api.alsa.disable-mixer = true
        api.alsa.soft-mixer = true
      }
    }
  }
]
